# Generated by Django 4.2.2 on 2023-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('id_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('worktime', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('date_hired', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
