# Generated by Django 4.2.2 on 2023-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_alter_employees_id_number_alter_employees_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
